# Generated by Django 2.2.7 on 2019-12-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
